# Generated by Django 3.0.7 on 2020-06-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20200623_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_moderador',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False),
        ),
    ]
